# Generated by Django 4.2 on 2023-04-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberlesson',
            name='short',
            field=models.CharField(blank=True, choices=[('Сокращенное', 'Сокращенные'), ('Обычное', 'Обычное')], max_length=255, verbose_name='Сокращенная пара?'),
        ),
    ]
